version: "3"

services:

  testrpc:
    image: trufflesuite/ganache-cli:v6.1.8
    ports:
      - 8545
    networks:
      - blockchain

  webpack_dev_server:
    build: ./services/app
    command: yarn start
    ports:
      - 8080:8080
    volumes:
      - ./services/app:/usr/src/app
    networks:
      - blockchain
      - client

  proof_service:
    build: ./services/proof
    ports:
      - 18861
    networks:
      - operator
    volumes:
      - ./services/proof/main.py:/root/rpyc/main.py

  aggregator:
    build: ./services/illuminati
    command: python -m aggregator --host 0.0.0.0 --port 5000
    ports:
      - 5000:5000
    depends_on:
      - testrpc
    networks:
      - blockchain
      - operator
    volumes:
      - ./services/illuminati/aggregator:/usr/src/app/aggregator

networks:
  blockchain:
  operator:
  client: