version: "3"

services:

  testrpc:
    image: trufflesuite/ganache-cli:v6.1.8
    ports:
      - 8545
    networks:
      - blockchain

  app:
    build: ./app
    command: yarn start
    ports:
      - 8080:8080
    volumes:
      - ./app:/usr/src/app
    networks:
      - blockchain

  # proof_service:
  #   build: ../roll_up
  #   working_dir: /root/roll_up
  #   command: flask serve
  #   depends_on:
  #     - testrpc
  #   networks:
  #     - blockchain

networks:
  blockchain: