version: "3"

services:

  testrpc:
    image: trufflesuite/ganache-cli:v6.1.8
    ports:
      - 8545
    networks:
      - blockchain

  proof_service:
    build: ./services/proof

  webpack_dev_server:
    build: ./services/app
    command: yarn start
    ports:
      - 8080:8080
    volumes:
      - ./services/app:/usr/src/app
    networks:
      - blockchain

  aggregator:
    build: ./services/prover
    command: python -m aggregator --host 0.0.0.0 --port 5000
    ports:
      - 5000:5000
    depends_on:
      - testrpc
    networks:
      - blockchain
    volumes:
      - ./services/prover/aggregator:/usr/src/app/aggregator

  test:
    build: ./services/test
    command: python test.py
    volumes:
      - ./services/test:/usr/src/app/test

networks:
  blockchain: