version: "3"

services:

  ethereum:
    build: ./services/ethereum
    ports:
      - 8545:8545
    networks:
      - blockchain

  webpack_dev_server:
    build: ./services/app
    command: yarn start
    ports:
      - 8080:8080
    volumes:
      - ./services/app/src:/usr/src/app/src
      - ./services/app/webpack.config.js:/usr/src/app/webpack.config.js
      - ./services/app/package.json:/usr/src/app/package.json
    networks:
      - blockchain
      - client
    env_file:
      - .default.env

  proof_service:
    build: ./services/proof
    ports:
      - 18861
    networks:
      - illuminati
    volumes:
      - ./services/proof/main.py:/root/rpyc/main.py

  wallet:
    build: ./services/wallet
    command: python -m signer --host 0.0.0.0 --port 5001
    ports:
      - 5001:5001
    networks:
      - client
    volumes:
      - ./services/wallet/signer:/usr/src/app/signer
    env_file:
      - .default.env

  aggregator:
    build: ./services/illuminati
    command: python -m aggregator --host 0.0.0.0 --port 5000
    ports:
      - 5000:5000
    depends_on:
      - ethereum
      - proof_service
    networks:
      - blockchain
      - illuminati
    volumes:
      - ./services/illuminati/aggregator:/usr/src/app/aggregator

networks:
  blockchain:
  illuminati:
  client:
